version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - echo "Running tests..."
      - python -m unittest discover
  build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 905418334417.dkr.ecr.us-east-1.amazonaws.com
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t python_app:latest .
      - docker tag python_app:latest 905418334417.dkr.ecr.us-east-1.amazonaws.com/python_app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 905418334417.dkr.ecr.us-east-1.amazonaws.com/python_app:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"Container-app-python","imageUri":"905418334417.dkr.ecr.us-east-1.amazonaws.com/python_app:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"905418334417.dkr.ecr.us-east-1.amazonaws.com/python_app:latest"}' > imageDetail.json
      - cat imagedefinitions.json

artifacts:
  files:
    - "**/*"
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
