version: "3.8"

services:
  blacklist:
    build: .
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=blacklist
      - API_KEY=my-secret-key
      - NEW_RELIC_APP_NAME=Blacklist
      - NEW_RELIC_LOG=stdout
      - NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
      - NEW_RELIC_LICENSE_KEY=319f3248ed269e4ed4fa356dd95cd9817fe8NRAL
      - NEW_RELIC_LOG_LEVEL=info
    restart: always
    networks:
      - app_net
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"

  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blacklist
    ports:
      - "5432:5432"
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app_net:
    driver: bridge
